export const HOME_QUOTES = [
  "Progress still counts when you take it one step at a time.",
  "A little patience can make room for a better answer.",
  "Small choices shape the days you remember.",
  "Make today a place where good habits can grow.",
  "You can begin again without starting from nothing.",
  "Steady effort has a quiet kind of strength.",
  "Leave a little space for the unexpected good.",
  "A thoughtful pause can change the direction of a day.",
  "Take care of what matters, one moment at a time.",
  "Your next step does not need to be a perfect one.",
  "Give your attention to what you can shape today.",
  "A calm start can carry you through a busy day.",
  "The effort you repeat becomes part of who you are.",
  "There is value in showing up with care.",
  "Let consistency do what urgency cannot.",
  "A better routine begins with one kind choice.",
  "You are allowed to grow at your own pace.",
  "Notice how far a series of small steps can take you.",
  "Make room for progress, not perfection.",
  "Today is a chance to choose with intention.",
  "The simplest plan is often the one you can keep.",
  "Protect a little time for the things that restore you.",
  "A good day can start with one clear priority.",
  "Build a life that feels steady from the inside.",
  "Rest is part of moving forward.",
  "Your attention is one of the kindest gifts you can give.",
  "Keep what helps, and let the rest become a lesson.",
  "A meaningful change can begin quietly.",
  "The work you do today can make tomorrow lighter.",
  "Choose the pace that lets you keep going.",
  "Every honest effort gives you something to build on.",
  "A little order can make space for more freedom.",
  "You do not have to solve everything today.",
  "Make your plans serve the life you want to live.",
  "Keep going with care, even when the pace is slow.",
  "A moment of gratitude can change what you notice.",
  "The next good choice is always within reach.",
  "Give yourself credit for the things you keep tending.",
  "Clear priorities make room for a fuller life.",
  "Start where you are and use what you have.",
  "Make space for the people and moments that matter.",
  "Steady days are built from thoughtful decisions.",
  "A fresh perspective can turn a setback into direction.",
  "Be present for the life you are building.",
  "Small acts of care add up over time.",
  "Let each day teach you something useful.",
  "Progress feels better when it reflects your values.",
  "Choose a next step that your future self will appreciate.",
  "Keep your goals close and your expectations kind.",
  "There is strength in beginning again with wisdom.",
] as const;

export const HOME_QUOTE_INDEX_KEY = "homeQuoteIndex";
